### ISSUE TITLE
matrix.select throws error in case of empty csv (only header)

### ISSUE THREAD

**Issue by an-bansal** [nmondal/njexl#6]
Steps
- Create/obtain an empty CSV file i.e. only with the header and no records.
- Create matrix for the CSV file : m = matrix(CSVFileName, ',')
- Select from the matrix : temp = m.select{ $['Associated Trade Id'] == tradeId  }()

Following errors are displayed.

Dec 02, 2015 6:13:39 PM com.noga.njexl.lang.internal.logging.LogFactory$LogImpl warn
WARNING: com.noga.njexl.lang.scripting.JexlScriptEngine.eval@211![149,170]: 'import 'java.lang.System' as SYS;CSVFileName = vars.get('CSVFileName');tradeId = vars.get('tradeID');m = matrix(CSVFileName, ',');temp = m.select{ $['Associated Trade Id'] == tradeId; }();OUT.println('TradeID : ' + vars.get('tradeID'));OUT.println('Trade Status : ' + vars.get('statusMsg'));OUT.println('TradeID in csv : ' + temp);if (!empty(temp)) { OUT.println('Trade inclusion to blotter Passed');SampleResult.setSuccessful(true);SampleResult.setResponseCode('1000');SampleResult.setResponseMessage('Test Passed');vars.put('outputResult', 'PASS'); } else { OUT.println('Trade inclusion to blotter Failed');SampleResult.setSuccessful(false);SampleResult.setResponseCode('999');SampleResult.setResponseMessage('Test Failed');vars.put('outputResult', 'FAIL'); }'  inaccessible or unknown property access at : ''Associated Trade Id'' 
Dec 02, 2015 6:13:39 PM com.noga.njexl.lang.internal.logging.LogFactory$LogImpl warn
WARNING: com.noga.njexl.lang.scripting.JexlScriptEngine.eval@211![149,170]: 'import 'java.lang.System' as SYS;CSVFileName = vars.get('CSVFileName');tradeId = vars.get('tradeID');m = matrix(CSVFileName, ',');temp = m.select{ $['Associated Trade Id'] == tradeId; }();OUT.println('TradeID : ' + vars.get('tradeID'));OUT.println('Trade Status : ' + vars.get('statusMsg'));OUT.println('TradeID in csv : ' + temp);if (!empty(temp)) { OUT.println('Trade inclusion to blotter Passed');SampleResult.setSuccessful(true);SampleResult.setResponseCode('1000');SampleResult.setResponseMessage('Test Passed');vars.put('outputResult', 'PASS'); } else { OUT.println('Trade inclusion to blotter Failed');SampleResult.setSuccessful(false);SampleResult.setResponseCode('999');SampleResult.setResponseMessage('Test Failed');vars.put('outputResult', 'FAIL'); }'  inaccessible or unknown property access at : ''Associated Trade Id'' 
Dec 02, 2015 6:13:39 PM com.noga.njexl.lang.internal.logging.LogFactory$LogImpl warn
WARNING: com.noga.njexl.lang.scripting.JexlScriptEngine.eval@211![139,187]: 'import 'java.lang.System' as SYS;CSVFileName = vars.get('CSVFileName');tradeId = vars.get('tradeID');m = matrix(CSVFileName, ',');temp = m.select{ $['Associated Trade Id'] == tradeId; }();OUT.println('TradeID : ' + vars.get('tradeID'));OUT.println('Trade Status : ' + vars.get('statusMsg'));OUT.println('TradeID in csv : ' + temp);if (!empty(temp)) { OUT.println('Trade inclusion to blotter Passed');SampleResult.setSuccessful(true);SampleResult.setResponseCode('1000');SampleResult.setResponseMessage('Test Passed');vars.put('outputResult', 'PASS'); } else { OUT.println('Trade inclusion to blotter Failed');SampleResult.setSuccessful(false);SampleResult.setResponseCode('999');SampleResult.setResponseMessage('Test Failed');vars.put('outputResult', 'FAIL'); }' method invocation error : 'select'
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.noga.njexl.lang.extension.datastructures.ListSet.get(ListSet.java:120)
	at com.noga.njexl.lang.extension.datastructures.Tuple.<init>(Tuple.java:57)
	at com.noga.njexl.lang.extension.dataaccess.DataMatrix.tuple(DataMatrix.java:218)
	at com.noga.njexl.lang.extension.dataaccess.DataMatrix._select_op_(DataMatrix.java:359)
	at com.noga.njexl.lang.extension.dataaccess.DataMatrix.select(DataMatrix.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.noga.njexl.lang.internal.MethodExecutor.execute(MethodExecutor.java:65)
	at com.noga.njexl.lang.internal.AbstractExecutor$Method.invoke(AbstractExecutor.java:328)
	at com.noga.njexl.lang.Interpreter.call(Interpreter.java:1958)
	at com.noga.njexl.lang.Interpreter.visit(Interpreter.java:2017)
	at com.noga.njexl.lang.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18)
	at com.noga.njexl.lang.Interpreter.visit(Interpreter.java:2278)
	at com.noga.njexl.lang.parser.ASTReference.jjtAccept(ASTReference.java:18)
	at com.noga.njexl.lang.Interpreter.visit(Interpreter.java:952)
	at com.noga.njexl.lang.parser.ASTAssignment.jjtAccept(ASTAssignment.java:18)
	at com.noga.njexl.lang.Interpreter.visit(Interpreter.java:1669)
	at com.noga.njexl.lang.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:38)
	at com.noga.njexl.lang.Interpreter.interpret(Interpreter.java:294)
	at com.noga.njexl.lang.ExpressionImpl.execute(ExpressionImpl.java:263)
	at com.noga.njexl.lang.ExpressionImpl.execute(ExpressionImpl.java:231)
	at com.noga.njexl.lang.scripting.JexlScriptEngine.eval(JexlScriptEngine.java:213)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:202)
	at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:69)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:745)

**Comment by an-bansal** [comment]
Verified!
