### ISSUE TITLE
Copying a global context to local context is giving error in xjMeter's JSR223 Sampler

### ISSUE THREAD

**Issue by japneet0212** [nmondal/njexl#7]
Getting an unsupported operator exception when copying a global context to local context in JSR223 Sampler in xJmeter:

 java.lang.Error: java.lang.UnsupportedOperationException: not supported!
	at com.noga.njexl.lang.ExpressionImpl.execMethod(ExpressionImpl.java:223)
	at com.noga.njexl.lang.Interpreter.call(Interpreter.java:1884)
	at com.noga.njexl.lang.Interpreter.visit(Interpreter.java:2000)
	at com.noga.njexl.lang.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18)

**Comment by japneet0212** [comment]
Closing as the issue is resolved.
